CREATE OR REPLACE FUNCTION FN_CALCULA_DV_CNPJ (P_CNPJ IN VARCHAR2) RETURN VARCHAR2 IS
    V_CNPJ_BASE VARCHAR2(12);
    V_SOMA1 NUMBER := 0;
    V_SOMA2 NUMBER := 0;
    V_DV1 NUMBER;
    V_DV2 NUMBER;
    V_RESTO NUMBER;
    V_ASCII NUMBER;
    V_PESOS_DV1 SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST(5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2);
    V_PESOS_DV2 SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST(6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2);
BEGIN
    V_CNPJ_BASE := UPPER(SUBSTR(REGEXP_REPLACE(P_CNPJ, '[^A-Za-z0-9]', ''), 1, 12));
    
    IF LENGTH(V_CNPJ_BASE) < 12 THEN
        RETURN NULL;
    END IF;
    
    FOR I IN 1..12 LOOP
        V_ASCII := ASCII(SUBSTR(V_CNPJ_BASE, I, 1)) - 48;
        V_SOMA1 := V_SOMA1 + (V_ASCII * V_PESOS_DV1(I));
        V_SOMA2 := V_SOMA2 + (V_ASCII * V_PESOS_DV2(I));
    END LOOP;
    
    V_RESTO := MOD(V_SOMA1, 11);
    IF V_RESTO < 2 THEN V_DV1 := 0; ELSE V_DV1 := 11 - V_RESTO; END IF;
    
    V_SOMA2 := V_SOMA2 + (V_DV1 * V_PESOS_DV2(13));
    
    V_RESTO := MOD(V_SOMA2, 11);
    IF V_RESTO < 2 THEN V_DV2 := 0; ELSE V_DV2 := 11 - V_RESTO; END IF;
    
    RETURN TO_CHAR(V_DV1) || TO_CHAR(V_DV2);
END;
/
